// packages/client/src/views/Start.svelte
<script>
  import { username, userid } from "../stores";
  import Button from "../components/Button.svelte";
  import Input from "../components/Input.svelte";
  import { v4 as uuidv4 } from "uuid";

  let name = "";

  username.useLocalStorage();
  userid.useLocalStorage();

  function onKeyDown(event) {
    if (event.detail.keyCode === 13 && name !== "") {
      submit();
    }
  }

  function submit() {
    username.set(name);
    userid.set(uuidv4());
  }
</script>

<style>
  main {
    align-items: center;
    display: flex;
    justify-content: center;
    width: 100vw;
    height: 100vh;
  }

  .input-wrapper {
    display: flex;
    max-width: 300px;
  }
</style>

<main>
  <div class="input-wrapper">
    <Input bind:value={name} on:onKeyDown={onKeyDown} placeholder="Username" />
    <Button margin="0 0 0 20px" on:onClick={submit} btnText="GO!" />
  </div>
</main>

// packages/client/src/routes/Start/Start.tsx
import React from 'react'
import styled from 'styled-components'
import { Formik } from 'formik'
import * as Yup from 'yup'
import Input from '../../components/Input'
import Button from '../../components/Button'
import { v4 as uuidv4 } from 'uuid'
import { useHistory } from 'react-router-dom'

const Wrapper = styled.div`
  align-items: center;
  display: flex;
  justify-content: center;
  width: 100vw;
  height: 100vh;
`

const InputForm = styled.form`
  display: flex;
  max-width: 300px;
`

const schema = Yup.object().shape({
  name: Yup.string().required('Required').max(30),
})

const Start: React.FC = () => {
  const history = useHistory()

  return (
    <Wrapper>
      <Formik
        initialValues={{ name: '' }}
        validationSchema={schema}
        onSubmit={({ name }, form) => {
          localStorage.setItem('username', name)
          localStorage.setItem('userId', uuidv4())
          form.resetForm()
          history.push('/chat')
        }}
      >
        {({ values, handleChange, handleSubmit, isSubmitting }) => (
          <InputForm onSubmit={handleSubmit}>
            <Input
              name="name"
              onChange={handleChange}
              placeholder="Username"
              value={values.name}
            />
            <Button
              type="submit"
              disabled={isSubmitting}
              btnText="GO"
              marginLeft="20"
            />
          </InputForm>
        )}
      </Formik>
    </Wrapper>
  )
}

export default Start
