// app/src/components/Input.svelte
<script>
  import { createEventDispatcher } from "svelte";

  export let value;
  export let placeholder;

  const dispatch = createEventDispatcher();

  function keydown(event) {
    dispatch("onKeyDown", event);
  }
</script>

<style>
  input {
    padding: 20px;
    width: 100%;
    border: none;
  }

  input:focus {
    outline: none;
  }
</style>

<input bind:value on:keydown={keydown} {placeholder} />

// src/components/Input.tsx
import React from 'react'
import styled from 'styled-components'

const InputElement = styled.input`
  padding: 20px;
  width: 100%;
  border-radius: 20px;
  background-color: #f3f3f3;

  &:focus {
    outline: none;
  }
`

interface InputProps {
  name: string
  onChange: (e: any) => void
  placeholder: string
  value: string
  type: string
}

const Input: React.FC<InputProps> = ({
  name,
  onChange,
  placeholder,
  value,
  type,
}) => {
  return (
    <InputElement
      name={name}
      type={type}
      onChange={onChange}
      placeholder={placeholder}
      value={value}
    />
  )
}

export default Input
