// packages/client/src/components/ChatLogMessage.svelte
<script>
  import { username } from "../stores/";
  import moment from "moment";

  export let message;
  let isGif = false;

  if (message.message.toLowerCase().match(/\.(gif)/g)) {
    isGif = true;
  }
</script>

<style>
  li {
    display: flex;
    font-size: 20px;
  }

  li:not(:first-child) {
    margin-top: 20px;
  }

  .inner {
    max-width: 80%;
  }

  img {
    width: 100%;
  }

  .me {
    justify-content: flex-end;
  }

  .other {
    justify-content: flex-start;
  }

  .message {
    font-size: 20px;
    padding: 20px;
  }

  .message--me {
    background-color: #fef8e6;
    border-radius: 20px 20px 3px 20px;
  }

  .message--other {
    background-color: #e8f4f9;
    border-radius: 20px 20px 20px 3px;
  }

  .time {
    color: #999999;
    font-size: 13px;
    margin-top: 10px;
  }
</style>

{#if message.username === $username}
  <li class="me">
    <div class="inner">
      <div class="message message--me">
        {#if isGif}
          <img src={message.message} alt="GIF" />
        {:else}{message.message}{/if}
      </div>
      <div class="time">{moment(message.time).format('LT')}</div>
    </div>
  </li>
{:else}
  <li class="other">
    <div class="inner">
      <div class="message message--other">
        {#if isGif}
          <img src={message.message} alt="GIF" />
        {:else}{message.message}{/if}
      </div>
      <div class="time">
        <strong>{message.username}</strong>
        | {moment(message.time).format('LT')}
      </div>
    </div>
  </li>
{/if}

// packages/client/src/components/ChatLogMessage.tsx
import React, { useState, useEffect } from 'react'
import { Message } from '../__generated__/types'
import styled from 'styled-components'
import { format } from 'date-fns'

const Wrapper = styled.li`
  display: flex;
  font-size: 15px;
  justify-content: flex-end;

  &:not(:first-child) {
    margin-top: 10px;
  }
`

const WrapperOther = styled(Wrapper)`
  justify-content: flex-start;
`

const Inner = styled.div`
  max-width: 80%;
`

const Msg = styled.div`
  padding: 20px;
  background-color: #fef8e6;
  border-radius: 20px 20px 3px 20px;
`

const MsgOther = styled(Msg)`
  background-color: #e8f4f9;
  border-radius: 20px 20px 20px 3px;
`

const Time = styled.div`
  color: #999999;
  font-size: 13px;
  margin-top: 10px;
`

const Gif = styled.img`
  width: 100%;
`

interface ChatLogMessageProps {
  message: Message
}

const ChatLogMessage: React.FC<ChatLogMessageProps> = ({ message }) => {
  const [userId] = useState(localStorage.getItem('userId') || '')
  const [isGif, updateIsGif] = useState(false)

  useEffect(() => {
    if (message.message.toLowerCase().match(/\.(gif)/g)) {
      updateIsGif(true)
    }
  }, [message])

  if (userId === message.userId) {
    return (
      <Wrapper>
        <Inner>
          <Msg>
            {isGif ? <Gif src={message.message} alt="GIF" /> : message.message}
          </Msg>
          <Time>{format(new Date(message.sent), 'H:mm a')}</Time>
        </Inner>
      </Wrapper>
    )
  }

  return (
    <WrapperOther>
      <Inner>
        <MsgOther>
          {isGif ? <Gif src={message.message} alt="GIF" /> : message.message}
        </MsgOther>
        <Time>
          <strong>{message.name}</strong> |{' '}
          {format(new Date(message.sent), 'H:mm a')}
        </Time>
      </Inner>
    </WrapperOther>
  )
}

export default ChatLogMessage
